workflows:
  android:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_HOME: $HOME/Library/Android/sdk
    scripts:
      - name: Clean
        script: ./gradlew clean
      - name: Assemble Debug
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
