workflows:
  android:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        ANDROID_HOME: /Users/builder/Library/Android/sdk
        ANDROID_SDK_ROOT: /Users/builder/Library/Android/sdk
    scripts:
      - name: Normalize Android SDK path
        script: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          unset ANDROID_SDK_ROOT
      - name: Clean
        script: ./gradlew clean
      - name: Assemble Debug
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
